- microceph/client/client.go
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>
> ceph: Increase disk add timeout

- snapcraft/commands/osd.start
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>
> snapcraft: Fix OSD pwd

- microceph/api/types/disks.go
- microceph/api/types/services.go
- microceph/ceph/bootstrap.go
- microceph/ceph/osd.go
- microceph/ceph/services.go
- microceph/cmd/microceph/cluster_sql.go
- microceph/cmd/microceph/init.go
- microceph/cmd/microceph/main.go
Add a few docstrings and cleanup linting, splitting out from PR#54
> Cleanup: linting fixes and remove some ununsed bits

- snapcraft.yaml
Signed-off-by: Chris MacNaughton <chris.macnaughton@canonical.com>
> Use sqlite from the archive rather than source

- microceph/ceph/bootstrap.go
> Refactor bootstrapping: split out monmap creation

- microceph/ceph/bootstrap.go
Also style cleanup (import ordering). This has been split out from PR #58
> Refactor bootstrapping: split out keyring creation

- microceph/ceph/bootstrap.go
> Refactor bootstrapping: split out mon init

- microceph/ceph/subprocess.go
> Refactor: add runner interface

- microceph/ceph/bootstrap.go
Signed-off-by: Peter Sabaini peter.sabaini@canonical.com
> Refactor bootstrapping: split out mgr init

- microceph/ceph/bootstrap.go
This PR is stacked on top of PR #63
> Refactor bootstrapping: split out msgr2

- microceph/ceph/bootstrap.go
This PR is stacked on top of PR #64
> Refactor bootstrapping: split out database

- microceph/ceph/bootstrap.go
> Refactor bootstrap: split out update database

- microceph/ceph/keyring.go
- microceph/ceph/monitor.go
- microceph/ceph/osd.go
- microceph/ceph/run.go
- microceph/ceph/snap.go
- microceph/ceph/subprocess.go
> Refactor: use runner interface

- microceph/ceph/bootstrap.go
> Refactor: split out mds and msgr2 init

- microceph/ceph/bootstrap_test.go
- microceph/ceph/configwriter_test.go
- microceph/ceph/testutils.go
> Factor out test utilities in a common base class

- microceph/ceph/bootstrap.go
- microceph/ceph/join.go
> ceph: Fix path default permissions

- microceph/ceph/osd.go
When we defer recording an OSD ID until after
the OSD is prepared, there is a long race that
another OSD can get setup with a duplicate ID.
Closes #94
Signed-off-by: Chris MacNaughton <chris.macnaughton@canonical.com>
> Record the new OSD id before formatting

- .github/workflows/tests.yml
- snapcraft.yaml
- snapcraft/commands/radosgw-admin
> Add support for rgw-admin

- docs/tutorial/install.rst
> Doc fix: use larger instance types in tutorial

- .github/workflows/tests.yml
- docs/explanation/fde-osd.rst
- docs/explanation/index.rst
- microceph/api/disks.go
- microceph/api/types/disks.go
- microceph/ceph/osd.go
- microceph/cmd/microceph/disk_add.go
- microceph/cmd/microceph/init.go
- snapcraft.yaml
- snapcraft/commands/osd.start
Add optional OSD disk encryption via LUKS and dm-crypt
> Add OSD encryption

- docs/explanation/index.rst
- docs/explanation/scaling-microceph.rst
Add some explanation around scaling up and failure domains
> Docs: scaling up

- microceph/ceph/osd.go
> Fix: make setting host failure domain more resilient

- microceph/database/schema.go
Add on delete cascade so foreign key integrity is preserved
Fixes: #49
> Fix: remove cluster members SQL

- docs/tutorial/update.rst
If the following was on purpose, please disregard this PR and close it.
The generated table of contents was as follows.
Tutorial
- Install Microceph using LXD
- Initial Setup
- Add OSDs
- Update management
- Disable automatic updates
- Updating microceph
3 items from the `update.rst` were shown up as the top level topics.
> Avoid multiple h1 level headings

- docs/how-to/service-migration.rst
* Fix hyperlinks to services
* Formatting of commands
* Mention the `status` command
This page should be updated later with a realistic example and command output.
> Update migrating services howto

- docs/how-to/service-placement.rst
This is a redo of a previous PR.
> docs: Review service placement howto

- docs/index.rst
This is a first pass review of the docs landing page. The opening paragraphs have been slightly reworded but I think we can still do better there.
I removed the Roadmap link as it merely pointed to the list of repository issues.
> docs: Review landing page

- docs/tutorial-2/index.rst
- docs/tutorial-2/single-node.rst
Leave this new tutorial hidden in the navigation for now. After the addition of another tutorial in a second PR the old tutorial material will be unpublished in a third PR.
> Add single-node tutorial

- .readthedocs.yaml
closes https://github.com/canonical/microceph/issues/207
> MicroCeph RTD deprecated config update

- .github/workflows/candidate-upgrade.yml
- .github/workflows/tests.yml
- tests/scripts/actionutils.sh
Add a test to run an upgrade from quincy/stable to local build on push
Also add a manual test to run a test from quincy/stable to quincy/candidate on demand
Some test refactoring
> Add upgrade tests

- dependabot.yml
Enable github dependabot for microceph
> Added dependabot support for MicroCeph

- docs/explanation/cluster-configurations.rst
- docs/explanation/cluster-scaling.rst
- docs/explanation/full-disk-encryption.rst
- docs/explanation/snap-content-interface.rst
- docs/how-to/configure-network-keys.rst
- docs/how-to/enable-alerts.rst
- docs/how-to/enable-metrics.rst
- docs/how-to/enable-service-instances.rst
- docs/how-to/migrate-auto-services.rst
- docs/how-to/remove-disk.rst
- docs/tutorial/multi-node.rst
- docs/tutorial/single-node.rst
Improve page titles and underlying filenames.
> docs: Review page titles and filenames

- docs/.custom_wordlist.txt
- docs/tutorial/single-node.rst
Move some words around and streamline. Make users more aware about loop file usage and their overhead.
> Refactor wording around loop file overhead

- README.md
Fix the emoji used in the README (Quickstart section).
Also fix some other formatting, like line length and better linking.
> docs: Fix README emoji

- .github/workflows/tests.yml
- .gitignore
- docs/.custom_wordlist.txt
- docs/reference/commands/disk.rst
- docs/tutorial/multi-node.rst
- microceph/api/disks.go
- microceph/api/types/disks.go
- microceph/ceph/osd.go
- microceph/client/disks.go
- microceph/cmd/microceph/disk_add.go
- microceph/cmd/microceph/disk_list.go
- microceph/cmd/microceph/disk_remove.go
- microceph/cmd/microceph/init.go
- microceph/common/constants.go
- tests/scripts/actionutils.sh
```
root@ubuntu-ceph-VLWH-MQIA:~# sudo microceph disk list
Disks configured in MicroCeph:
+-----+----------+------+
| OSD | LOCATION | PATH |
+-----+----------+------+
Available unpartitioned disks on this system:
+---------------+----------+------+--------------------------------------------------------+
|     MODEL     | CAPACITY | TYPE |                          PATH                          |
+---------------+----------+------+--------------------------------------------------------+
| QEMU HARDDISK | 10.00GiB | scsi | /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_lxd_vol--9I1F |
+---------------+----------+------+--------------------------------------------------------+
| QEMU HARDDISK | 10.00GiB | scsi | /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_lxd_vol--EBBT | …
```
> Added flag to add all available devices as OSDs

- microceph/cmd/microceph/disk_list.go
- microceph/cmd/microceph/init.go
- tests/scripts/actionutils.sh
```
$ sudo microceph disk list --json
{"ConfiguredDisks":[{"osd":1,"path":"/dev/loop5","location":"juju-3b5009-0"}],"UnpartitionedDisks":[]}
```
> Added json output flag to Disk List

- docs/reference/index.rst
- docs/reference/microceph-charm.rst
Summarise the microceph charm and point to the Charmhub.
> docs: Introduce microceph charm into the doc set

- docs/reference/commands/cluster.rst
- microceph/cmd/microceph/cluster_bootstrap.go
> Fix #303: Introduce flag --microceph-ip for cluster bootstrap

- .github/workflows/tests.yml
- snap/snapcraft.yaml
- tests/scripts/actionutils.sh
> Fix: allow mount observe

- microceph/cmd/microceph/cluster_bootstrap.go
Increased MicroCeph bootstrap timeout to 1 minute.
> Increased bootstrap timeout

- docs/.custom_wordlist.txt
- docs/index.rst
Users should be informed about the possibility of adding Pro to their Ceph nodes.
> docs: Add a pointer to Ubuntu Pro

- .github/workflows/q2q-candidate-upgrade.yml
- .github/workflows/q2r-candidate-upgrade.yaml
- .github/workflows/r2r-candidate-upgrade.yaml
Add network space to upgrade tests
- [x ] Bug fix (non-breaking change which fixes an issue)
> Fix upgrade tests

- snapcraft/commands/common
- snapcraft/commands/mds.start
- snapcraft/commands/mgr.start
- snapcraft/commands/mon.start
- snapcraft/commands/osd.start
- snapcraft/commands/rados
- snapcraft/commands/rgw.start
Ensure ceph.conf points to the correct run dir
Fixes: #356
> Fix: wait until config has settled before starting services

- microceph/cmd/microceph/disk_list.go
buglet in help string
- [x ] Documentation update (Doc only change)
> Fix: doc buglet

- tests/scripts/actionutils.sh
Add function wait_for_rgw in test scripts.
The function takes number of daemons as
parameter and checks against ceph status.
> Add wait_for_rgw in test scripts

- microceph/ceph/rgw.go
- microceph/ceph/rgw_test.go
- microceph/ceph/services_placement_rgw.go
Fixes incomplete monitor address population for RGW configuration file.
Fixes #359 
strengthened the unit tests
> Fix monitor addresses in rgw.conf

- docs/.wordlist.txt
- docs/how-to/integrate-keystone.rst
Doc changes; adds a how to for configuring RGW Keystone config keys in MicroCexph
Fixes #NA
Doc only change
> Added a How-To for configuring Keystone in MC

- microceph/cmd/microceph/disk_list.go
Adds a flag to query just the local OSDs on the current host.
Fixes #NA
TODO: Add tests
> Added a flag to query host OSDs only

- docs/.sphinx/_templates/header.html
- docs/custom_conf.py
- docs/how-to/remove-disk.rst
I'm experimenting with building the MicroCeph docs as part of the MicroCloud documentation, and noticed some small issues.
This PR fixes them.
> Small doc fixes

- docs/how-to/integrate-keystone.rst
- microceph/ceph/config.go
Add following rgw swift options
* rgw_swift_versioning_enabled
* rgw_swift_enforce_content_length
* rgw_swift_custom_header
Manual testing
> Add RGW Swift config options

- docs/explanation/taking-snapshots.rst
- docs/tutorial/mount-block-device.rst
- docs/tutorial/mount-cephfs-share.rst
Documentation change
Doc change, no need new CI tests.
> Added snapshot docs

- .github/workflows/tests.yml
- snap/snapcraft.yaml
> MicroCeph Squid: Core24

- docs/.wordlist.txt
Adding CephFS to wordlist to fix failing spelling check.
> Add CephFS to wordlist

- docs/how-to/index.rst
- docs/tutorial/index.rst
Fixes up the documentation indexes
> Docs: fix indexes

- snap/snapcraft.yaml
> Build from noble-proposed

- .github/workflows/r2s-edge-upgrade.yaml
> Test: upgrade update

- docs/.sphinx/spellingcheck.yaml
- docs/how-to/index.rst
- docs/how-to/major-upgrade.rst
- docs/reference/index.rst
- docs/reference/release-notes.rst
> Doc: add release info

- docs/reference/index.rst
- docs/reference/release-notes.rst
> Doc: release note and ref fix

- docs/reference/release-notes.rst
Add a warning about strict cluster host checking
> Doc: note clustering change

- .github/.jira_sync_config.yaml
Add config for the GH/Jira bot
> Add config for the GH/Jira bot

- docs/Makefile
> Add a `--port` parameter to the `run` target in the Makefile

- .github/workflows/r2s-edge-upgrade.yaml
> Tests: upgrade from reef to squid/candidate

- docs/explanation/cluster-maintenance.rst
- docs/explanation/index.rst
- docs/how-to/index.rst
- docs/how-to/perform-cluster-maintenance.rst
- docs/reference/commands/cluster.rst
> docs: add maintenance mode documentation

- .github/workflows/s2s-candidate-upgrade.yaml
Add upgrade test for s/candidate to s/stable
> Test: upgrade s/candidate to s/stable

- microceph/ceph/configwriter.go
Workaround for https://tracker.ceph.com/issues/70390
> Hotfix: disable Elastic Shared Blobs

- snap/snapcraft.yaml
ceph-logs slot for grafana-agent scraping
not tested separately
> Added a content slot for exposing ceph logs

- snap/snapcraft.yaml
- snapcraft/commands/common
- snapcraft/commands/mds.start
- snapcraft/commands/mgr.start
- snapcraft/commands/mon.start
- snapcraft/commands/osd.reload
- snapcraft/commands/osd.start
- snapcraft/commands/rbd-mirror.start
- snapcraft/commands/rgw.start
- tests/scripts/actionutils.sh
Increases ulimit for Ceph services
Fixes: #524
> fix: increase limits for nofile, nproc

- .gitignore
- microceph/Makefile
Adds the capability for unit test runs to produce coverage reports.
> Add support for coverage reporting

- docs/reference/commands/disk.rst
- microceph/cmd/microceph/disk_add.go
Update for the disk add doc
Partly fixes #544 
- Documentation update (change to documentation only)
> [!NOTE]
> All functional changes should accompany corresponding tests (unit tests, functional tests, etc.).
Please describe the addition/modification of tests done to verify this change. Also list any
relevant details for your test configuration.
> doc: disk add update

- .github/workflows/tests.yml
- microceph/ceph/nfs.go
- microceph/ceph/nfs_test.go
- tests/scripts/actionutils.sh
Please include a summary of the changes and the related issue. Also include relevant
motivation and context. List any dependencies that are required for this change.
If it fixes a reported issue, mention it here, i.e.:
Fixes #<issue-number>
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Clean code (code refactor, test updates; does not introduce functional changes)
- Documentation update (change to documentation only)
> [!NOTE]
> All functional changes should accompany corresponding tests (unit tests, functional tests, etc.).
Please describe the addition/modification of tests done to …
> NFS: Create only one OSD pool for NFS Ganesha

- docs/reference/release-notes.rst
- Make heading more descriptive
- Fix section heading nesting
- Documentation update (change to documentation only)
Existing tests
> doc: fix section headings

- .github/workflows/tests.yml
- tests/scripts/actionutils.sh
Replace dodgy sed with json parsing
- Clean code (code refactor, test updates; does not introduce functional changes)
> [!NOTE]
> All functional changes should accompany corresponding tests (unit tests, functional tests, etc.).
Please describe the addition/modification of tests done to verify this change. Also list any
relevant details for your test configuration.
> ci: robustify osd check

- tests/scripts/actionutils.sh
Inc. timeout as on busy systems can take some time to bring up loop devs
> ci: incr. wait time for osds
