microceph/common/state.go

Create interface for easier mocking; split out of PR #54

Add an interface to access the microcluster state

---

microceph/ceph/bootstrap.go

This PR is stacked on top of PR #62

Refactor bootstrapping: split out mds init

---

.github/workflows/tests.yml
snapcraft.yaml
snapcraft/commands/osd.start

In addition to checking for admin socket presence, also check there is a process listening at the other end in order to prevent false positives in checking ceph-osd startup due to a stale socket file

Fix OSD startup script liveness check

---

snapcraft.yaml

This is needed to access /usr/bin/ss.
Signed-off-by: Stéphane Graber <stephane.graber@canonical.com>

snapcraft: Add network-observe to osd

---

snapcraft.yaml
snapcraft/commands/osd.start

This fixes quite a few issues:
- Make logging work (so we can actually debug issues)
- Don't use ss or lsof as both get blocked by snapd, use netcat instead for OSD checking
- Fix rbd/osd issues using a layout entry for rados-classes

Fix rbd issues

---

microceph/cmd/microceph/init.go

I'm guessing this was missed during refactoring.

Use port 7443 for init to bring inline with bootstrap/join

---

snapcraft.yaml

We cannot assume that these directories will be empty which causes the snap layotu handling to fail. Changing to bind works around this issue.
Closes #122

Replace symlink with bind-mount for default ceph directories

---

snapcraft.yaml
snapcraft/commands/rados

Add microceph.rados command as part of snapcraft.
rados utility is used in some of the ceph libraries like [1] and so expose the utility as part of microceph.
[1] https://github.com/juju/charm-helpers

add rados command to microceph

---

docs/tutorial/index.rst
docs/tutorial/install.rst
docs/tutorial/update.rst

This PR adds a section in the installation docs that specifies the recommended way to manage upgrades.

Update install docs with upgrade management section

---

.github/workflows/tests.yml
microceph/api/configs.go
microceph/api/endpoints.go
microceph/api/services.go
microceph/api/types/configs.go
microceph/ceph/config.go
microceph/ceph/config_test.go
microceph/ceph/osd.go
microceph/ceph/services.go
microceph/ceph/services_test.go
microceph/ceph/snap.go
microceph/client/client.go
microceph/cmd/microceph/cluster.go
microceph/cmd/microceph/cluster_config.go
microceph/cmd/microceph/cluster_config_get.go
microceph/cmd/microceph/cluster_config_list.go
microceph/cmd/microceph/cluster_config_reset.go
microceph/cmd/microceph/cluster_config_set.go
microceph/go.mod
microceph/go.sum

Added command
```microceph cluster config set/get/reset/list```
for managing configs (currently limited to cluster_network and public_network)

Add Cluster config management to microceph

---

.github/workflows/tests.yml
microceph/ceph/osd.go
microceph/ceph/snap.go

```
ubuntu@bastion:~$ sudo microceph disk add  /dev/disk/by-id/virtio-d15384b1-7159-4a91-a --wipe --encrypt
Error: Failed adding new disk: Encryption unsupported on this machine: Missing dm_crypt module: stat /sys/module/dm_crypt: no such file or directory
Use "sudo snap connect microceph:dm-crypt" to enable disk encryption.
```

Add checks for dmcrypt intf connection

---

.github/workflows/tests.yml
snap/hooks/install
snap/hooks/post-refresh
snap/snapcraft.yaml

This content-interface exposes ceph configuration, creds and metadata to enable deep integration with a MicroCeph cluster

Add content-interface for ceph config

---

microceph/ceph/crush.go
microceph/ceph/osd.go
microceph/ceph/osd_test.go

Remove the osd rule to ensure new pools get the upgraded crush rule

Fix: remove automatic crush rule on upgrading

---

microceph/go.mod
microceph/go.sum

A fix was released in canonical/microcluster@f82e569 solving a deadlock issue that caused timeouts when accessing microcluster apis.

chore: update microcluster dependency

---

docs/how-to/index.rst
docs/how-to/service-migration.rst
microceph/api/services.go
microceph/ceph/monitor.go
microceph/ceph/rgw.go
microceph/ceph/services.go
microceph/ceph/services_test.go
microceph/client/services.go
microceph/cmd/microceph/cluster.go
microceph/cmd/microceph/cluster_migrate.go
microceph/cmd/microceph/disable_rgw.go

Implement a new command that migrates automatic services (mon, mgr,
mds) from a source to a dest node.
Manual testing:
```
ubuntu@bc-0:~$ sudo microceph status
MicroCeph deployment summary:
- bc-0 (10.0.8.6)
Services: mds, mgr, mon, rgw, osd
Disks: 1
- bc-1 (10.0.8.65)
Services: osd
Disks: 1
- bc-2 (10.0.8.106)
Services: mds, mgr, mon, osd
Disks: 1
- bc-3 (10.0.8.107)
Services: mds, mgr, mon
Disks: 0
ubuntu@bc-0:~$ sudo microceph cluster migrate bc-0 bc-1
ubuntu@bc-0:~$ sudo microceph status
MicroCeph deployment summary:
- bc-0 (10.0.8.6)
Services: rgw, osd
Disks: 1
- bc-1 (10.0.8.65)
Services: mds, mgr, mon, osd
Disks: 1
- bc-2 (10.0.8.106)
Services: mds, mgr, mon, osd
Disks: 1
- bc-3 (10.0.8.107)
Services: mds, mgr, mon
Disks: 0
ubuntu@bc-0:~$ sudo microceph.ceph -s
cluster:
id: …
```

Migrate auto services

---

docs/how-to/service-migration.rst

As discussed with @UtkarshBhatthere, "automatic services" does not sound right. Rename this to "automatically-provisioned services".
Re-title page to something more direct and short (for the navigation menu).
Improve and refactor wording.

docs: Review migrating services howto

---

.github/workflows/tests.yml
tests/scripts/actionutils.sh

Add a GH action runner job to do multi node tests by setting up 4 privileged lxc containers on the runner with loopback devices.
Also refactor tests to utilize a helper script.

Multinode testing

---

docs/tutorial/add_osds.rst
docs/tutorial/initial_setup.rst
docs/tutorial/update.rst

MicroCeph has been granted aliases for ceph commands, update the docs to reflect this.

Doc: use ceph alias

---

snap/snapcraft.yaml

For reading certificates, dumping crushmaps and similar operations

Allow access to $HOME for the ceph command

---

docs/how-to/cluster-cfg.rst

{public,cluster}_network values passed to microceph will be written to the Ceph config database as {public,cluster}_network as is. That means the values are used as cluster wide setting instead of per-node config.
According to the upstream configuration reference[1], the previous example doesn't make sense as 10.5.2.165 looks like a real IP address of a node instead of a network address. Let's use a network address and be clearer about the reset step too.
```
$ sudo microceph cluster config set cluster_network 192.168.102.0/24
$ sudo microceph.ceph config dump
WHO     MASK  LEVEL     OPTION           VALUE             RO
global        advanced  cluster_network  192.168.102.0/24  *
```
[1] https://docs.ceph.com/en/latest/rados/configuration/network-config-ref/#confval-cluster_network

Use appropriate {public,cluster}_network examples

---

microceph/ceph/configwriter.go
microceph/ceph/testutils.go
microceph/common/constants.go

```
$ cd /var/snap/microceph/current/conf/
$ whoami
ubuntu
$ ll
total 24
drwxr-xr-x 2 root root 4096 Aug 29 08:43 ./
drwxr-xr-x 4 root root 4096 Aug 29 08:43 ../
-rw------- 1 root root  151 Aug 29 08:43 ceph.client.admin.keyring
-rw-r----- 1 root root  263 Aug 29 08:44 ceph.conf
-rw-r----- 1 root root  102 Aug 29 08:44 ceph.keyring
-rw-r--r-- 1 root root   64 Aug 29 08:43 metadata.yaml
$ cat ceph.keyring 
cat: ceph.keyring: Permission denied
$ cat ceph.conf 
cat: ceph.conf: Permission denied
$ cat ceph.client.admin.keyring 
cat: ceph.client.admin.keyring: Permission denied
$ sudo cat ceph.keyring 
[client.admin]
key = AQCyr+1kE9cxChAA8A5pVgteASeXh24Hi796Sw==
```

Update /conf file permissions

---

snap/snapcraft.yaml

Fix: add the ceph-conf helper

---

docs/tutorial-2/index.rst
docs/tutorial-2/multi-node.rst
docs/tutorial-2/single-node.rst

Add a tutorial on setting up a multi-node cluster.
Make adjustments to the existing single-node cluster tutorial to maintain consistency.
See PR  #200 for context.

Add multi-node tutorial

---

docs/explanation/fde-osd.rst

This is a stop gap measure for #190. There is an issue to track this at https://bugs.launchpad.net/snapd/+bug/2034585 . For a more permanent workaround we could alternatively also restart microceph.daemon in an interface hook after dm-crypt connection, however it'd be preferable to fix this in snapd so as to avoid API interruptions.

Doc: need to restart microceph.daemon after dm-crypt conn

---

docs/tutorial/single-node.rst

Minor inaccuracy: support for loopback devices needs to land in snapd not Ceph, but this is a bit of a detail so just pared it down to "Development"

Doc fix: loopback device

---

microceph/ceph/bootstrap.go
microceph/ceph/config.go
microceph/ceph/configwriter.go
microceph/ceph/configwriter_test.go
microceph/ceph/rgw.go

Make ceph.conf world-readable

---

microceph/api/disks.go
microceph/api/types/disks.go
microceph/ceph/osd.go
microceph/ceph/osd_test.go
microceph/cmd/microceph/disk_add.go

This PR aims to add the needed support for write-ahead log (WAL) and database devices when adding OSDs to the cluster.

Add the WAL and DB devices for the disk-add command

---

microceph/ceph/osd.go
microceph/ceph/osd_test.go
microceph/cmd/microceph/disk_remove.go

Fix regexp for stopping OSD services.
Don't treat a failure to stop an OSD service as fatal, might be down already.
Increase default timeout and retries, the default was overly optimistic.
Test cleanup.

Fixes for disk remove issues

---

microceph/cmd/microceph/cluster_remove.go
microceph/cmd/microceph/cluster_remove_test.go

In testing we are seeing situations where a quorum could not be established. Require a min. of 3 mons in the non-forced case to prevent this.

Fix: tighten requirements for removing nodes

---

microceph/cmd/microceph/cluster_bootstrap.go
microceph/cmd/microceph/cluster_join.go
microceph/cmd/microceph/init.go

Increase timeouts on clustering operations. Setting up the dqlite infra can be resource intensive and might land into timeouts on loaded systems otherwise.

Try harder when clustering

---

.github/workflows/tests.yml
microceph/api/disks.go
microceph/api/types/disks.go
microceph/ceph/osd.go
microceph/cmd/microceph/disk_add.go
microceph/database/disk_extras.go
snap/snapcraft.yaml

Add support for auto-creating loopback backing for OSDs

Support OSD file backing

---

README.md

* Repair table of contents - links were broken
* Remove documentation content (**Quickstart** section)
* Add **Documentation** section, and point to published content
* Replace **How Can I Contribute** section with **Project & community** section
* Add **License** section
Proposed organisation is based on consistency across projects. Some customisation is fine (e.g. table of contents).

docs: Fix up section headers in README

---

microceph/cmd/microceph/main.go
snap/snapcraft.yaml

Build version string from Ceph package version, suffixed by snap git hash

Version: set meaningful version string

---

.github/workflows/tests.yml
.gitignore
microceph/api/endpoints.go
microceph/api/pool.go
microceph/api/types/pool.go
microceph/ceph/osd.go
microceph/client/pool.go
microceph/cmd/microceph/main.go
microceph/cmd/microceph/pool.go

This PR implements the pool endpoint and inside it, the 'set-rf' command to set the replication factor of a list of pools.

Implement the 'pool' endpoint and 'set-rf' command

---

.github/workflows/tests.yml
microceph/api/endpoints.go
microceph/api/log.go
microceph/api/types/log.go
microceph/ceph/log.go
microceph/client/log.go
microceph/cmd/microceph/log.go
microceph/cmd/microceph/main.go

This PR implements the setter and getter for log levels as used by the microceph daemon. It needs to jump through some hoops, as the lxd libraries don't expose this functionality themselves.

Implement the operations for getting and setting log-level

---

microceph/common/storage.go
microceph/common/storage_test.go
microceph/constants/constants.go

Edit: adding a local unit test run as the CI for unittests is broken:
```
peter@pirx ~/src/microceph/microceph ±fix/storage-unit-test » make check-unit 
go test ./...
?   	github.com/canonical/microceph/microceph/api	[no test files]
?   	github.com/canonical/microceph/microceph/api/types	[no test files]
?   	github.com/canonical/microceph/microceph/client	[no test files]
?   	github.com/canonical/microceph/microceph/cmd/microcephd	[no test files]
?   	github.com/canonical/microceph/microceph/constants	[no test files]
?   	github.com/canonical/microceph/microceph/database	[no test files]
?   	github.com/canonical/microceph/microceph/interfaces	[no test files]
?   	github.com/canonical/microceph/microceph/mocks	[no test files]
?   	github.com/canonical/microceph/microceph/tests	[no test …
```

Fix storage unit test

---

microceph/go.mod

Make it a direct dependency (otherwise the "go get" during build dirties the worktree)

Fix: move logrus to direct dep

---

.github/workflows/q2q-candidate-upgrade.yml
.github/workflows/q2r-candidate-upgrade.yaml
.github/workflows/r2r-candidate-upgrade.yaml
.github/workflows/tests.yml
microceph/ceph/config.go
microceph/ceph/start.go
tests/scripts/actionutils.sh

Fixes: #318
Ensure we populate the config key value db with required values if not present. Newer microceph version set these values on bootstrap, older releases might be missing them
Also add some testing for ceph.conf

Fix: ensure backward compat config

---

snap/snapcraft.yaml

Don't check untracked files so as not to fail for parts/ and stage/ dirs

Fixup build check

---

snap/snapcraft.yaml

Ceph has a dependency on distutils, which was removed from the packaging since it was an undeclared package dependency. This change adds setuptools package to work around this dependency.
Since distutils has been removed from python 12, this also reverts to core22.

Add setuptools dependency

---

microceph/ceph/join.go

Changes the decision logic for spawning new services at join. We now create the record in same transaction so that stale records do not cause more than 3 auto services to be spawned.
Fixes #351 
Manual tests using charm microceph (node count 4)

Fix: 4 Mon problem

---

microceph/api/servers.go
microceph/ceph/start.go
microceph/cmd/microceph/init.go
microceph/cmd/microcephd/main.go
microceph/go.mod
microceph/go.sum

This introduces a bit more robust schema upgrade processing, as well as better error handling during first start.
In particular, during an upgrade, the cluster will report its current status instead of blocking. The table below shows `microceph cluster list` output when 1 node is refreshed and awaiting the upgrade to appear on all nodes before proceeding to apply the update:
```
+--------+----------------+-------+-----------------------------+---------------+
|  NAME  |    ADDRESS     |  ROLE |         FINGERPRINT         |    STATUS     |
+--------+----------------+-------+-----------------------------+---------------+
| micro0 | 127.0.0.1:9000 | voter | c3d485471729f2f04f6401530f7 |   UPGRADING   |
+--------+----------------+-------+-----------------------------+---------------+
| …
```

Update microcluster dependency

---

microceph/ceph/pre_remove_test.go
microceph/ceph/remove.go
microceph/cmd/microceph/cluster_remove.go
microceph/cmd/microcephd/main.go

Closes #255 
As discussed in Riga, this refactors the node removal process to rely on the microcluster API instead of directly implementing removal in the MicroCeph CLI.
The main changes are that the `removeNode` function and all its helpers have been moved to the `ceph` package. The `removeNode` function itself has been wrapped in a `PreRemove` to match the corresponding hook in microcluster. Now in the CLI, we can simply call `DeleteClusterMember` and the `PreRemove` hook will automatically execute on that node as it is passed to microcluster when we call `app.Start`.
This will allow MicroCloud to utilize MicroCeph's API to tear down the cluster in case of an error during initialization. Additionally, it cleans up MicroCeph so there isn't so much internal implementation in the CLI …

Use microcluster API to remove cluster members

---

.github/workflows/tests.yml
microceph/ceph/config.go
snapcraft/commands/common
tests/scripts/actionutils.sh

With the from PR #378 microcephd daemons now wait for all nodes to be on the same schema level in a multinode upgrade scenario. However we used to depend on the microcephd to update the `run dir` parameter in ceph.conf; for sequential updates (where we iteratively upgrade nodes while keeping the cluster operational) this creates a circular dependency.
This PR removes the need for updateing run dir during an upgrade.
Also contains func test improvements to verify the sequential upgrade scenario.
Fixes #386 
Functional tests updated

Fix run dir issues

---

snap/snapcraft.yaml

`CRAFT_ARCH_TRIPLET` is deprecated for core22 and doesn't exist for core24 as described [here](https://snapcraft.io/docs/reference-architectures#core22).
The patch also fixes the following warnings during the build that could also be seen in "Build microceph snap" job during "Build snaps" step for every PR:
> CRAFT_ARCH_TRIPLET is deprecated, use CRAFT_ARCH_TRIPLET_BUILD_{ON|FOR}
Fixes #-
I tested it locally using `snapcraft pack -v`. The deprecation warning is no longer there.

snap/snapcraft: replace deprecated CRAFT_ARCH_TRIPLET with CRAFT_ARCH_TRIPLET_BUILD_FOR

---

.github/workflows/tests.yml
docs/reference/commands/cluster.rst
microceph/api/configs.go
microceph/api/types/configs.go
microceph/cmd/microceph/cluster_config_reset.go
microceph/cmd/microceph/cluster_config_set.go
tests/scripts/actionutils.sh

Allow the operator to skip daemon restart when applying bulk configurations to prevent repeated restarts of the service.
Added CI test to bombard the cluster with RGW configs but restart the RGW deamon only for the last config set. The expectation is that RGW IO tests should function as they did before the configs.

Allow skipping daemon restart post config op

---

docs/Makefile

`woke-install` is needed to run woke on the docs, but it is not required for building the documentation.

doc: remove `woke-install` as prereq for building the docs

---

.github/workflows/tests.yml
snap/snapcraft.yaml
tests/scripts/actionutils.sh

Add interfaces. Allow loading the rbd kernel module and add the microceph-support interface which allows additional block device types
Fixes #254  #251
As a test using an lvm vol as an OSD. RBD map support is not complete yet.

Add interfaces: rbd kernel module and support

---

.github/workflows/tests.yml
microceph/api/pool.go
microceph/api/servers.go
microceph/api/types/pool.go
microceph/ceph/osd.go
microceph/client/pool.go
microceph/cmd/microceph/pool.go

`PUT /1.0/pools-op` lets you set the replication size for several OSD pools. 
This PR adds the ability to fetch the current sizes (and some other relevant OSD pool information) via `GET /1.0/pools`. The goal of this is to obtain the correct OSD pool names to supply to `PUT /1.0/pools-op`, as well as to determine what the current size of each pool is. 
As discussed on mattermost: https://chat.canonical.com/canonical/pl/g3heo1kmz7r6db39re9qyzfw4w

Fetch current OSD pool configuration over the API

---

microceph/ceph/bootstrap.go
microceph/ceph/config.go
microceph/ceph/config_test.go
microceph/ceph/crush.go
microceph/cmd/microceph/cluster_config_get.go
microceph/cmd/microceph/cluster_config_reset.go
microceph/cmd/microceph/cluster_config_set.go

Adds support for RO cluster configs and exposes public_network as a RO config.
Fixes #353 

Adds support for RO cluster configs

---

.github/workflows/tests.yml
microceph/ceph/bootstrap.go
microceph/ceph/config.go
tests/scripts/actionutils.sh

Small PR which adds square brackets around mon host addresses in `ceph.conf` if IPv6 is used.
Closes https://github.com/canonical/microceph/issues/424.

Use square brackets around IPv6 in ceph.conf

---

microceph/cmd/microceph/cluster_bootstrap.go

Wait for microcephd readiness before attempting to bootstrap. Depending on machine load this can occasionally lead to a race otherwise

Bootstrap: wait for daemon

---

.github/workflows/tests.yml
docs/.custom_wordlist.txt
docs/how-to/index.rst
docs/how-to/perform-site-failover.rst
docs/reference/commands/remote-replication-rbd.rst
microceph/api/ops_replication.go
microceph/api/types/replication.go
microceph/ceph/rbd_mirror.go
microceph/ceph/rbd_mirror_test.go
microceph/ceph/replication.go
microceph/ceph/replication_rbd.go
microceph/ceph/test_assets/rbd_mirror_promote_secondary_failure.txt
microceph/client/remote_replication.go
microceph/cmd/microceph/remote_replication_rbd.go
microceph/cmd/microceph/remote_replication_rbd_demote.go
microceph/cmd/microceph/remote_replication_rbd_promote.go
microceph/constants/constants.go
tests/scripts/actionutils.sh

This change contains feature work to perform promotion/demotion for ALL pools across the cluster.

MicroCeph Remote Replication (3/3): Site Failover/Failback 

---

microceph/ceph/start.go
microceph/ceph/start_test.go

This patchset modifies the microcephd component so that it sets the 'require-osd-release' config option on startup, if needed. That is, in case the new (current) Ceph version is ahead of what the OSD's are currently running.
Unit testing is provided for this change.

Set the 'require-osd-release' option on startup

---

snap/snapcraft.yaml

Prometheus module needs python3-packaging

Fix: add python3-packaging

---

.github/workflows/tests.yml
tests/scripts/actionutils.sh

Test: upgrade reef to local build

---

.github/workflows/r2s-edge-upgrade.yaml

Test: add reef to squid upgrade test

---

tests/scripts/actionutils.sh

Adjust the number of iterations for the 'verify_health' bash helper. This is apparently needed for the 'require-osd-release' functionality recently introduced.

Adjust 'verify_health' iterations

---

.github/workflows/tests.yml
microceph/ceph/start.go
microceph/ceph/start_test.go

Increase timings for setting OSD release requirements

Fix: increase timings for osd release

---

microceph/ceph/rbd_mirror.go

MicroCeph attempts to disable the remote pool mirroring just after it disables it for the local pool. Sometimes this operation is performed before the new state has propagated to the remote cluster. Adding a retry here to attempt the disablement for remote pool again.

Add retry for secondary pool mirroring disablement

---

microceph/ceph/services.go

Adds a patch to remove mon.host entries on mon service cleanup.
Fixes #444 
CI

Backport mon.host entry cleanup from main to reef

---

.github/workflows/tests.yml
microceph/api/services.go
microceph/api/types/services.go
microceph/ceph/config.go
microceph/ceph/services_placement_rgw.go
tests/hurl/services-mon.hurl
tests/scripts/actionutils.sh

Add an api endpoint to get mon addresses

---

HACKING.md

Add some missing dependencies for running unit test and static checks locally.
Created a LXD VM and install the following dependencies, and make sure `make check-unit` and `make check-static` can run without issues.
```bash
sudo apt update
sudo apt install gcc make shellcheck 
sudo add-apt-repository ppa:dqlite/dev 
sudo apt install libdqlite-dev
sudo snap install go --classic
export PATH=$PATH:$HOME/go/bin
git clone https://github.com/canonical/microceph.git
cd microceph/microceph
make
```

doc: improve HACKING.md

---

docs/Makefile

When trying to run my local build of the docs, I run into this:
`ERROR:    [Errno 98] error while attempting to bind on address ('127.0.0.1', 8000): address already in use
make: *** [Makefile:62: run] Error 1`
Port 8000 seems to be a poor choice to use as it is very common, so I have modified the Makefile to use a different, less common port.

Use the less common TCP port 18000

---

snap/snapcraft.yaml

Running on riscv64 requires the libatomic1 package.

snapcraft.yaml: add libatomic1 dependency

---

microceph/ceph/start.go
snap/snapcraft.yaml
snapcraft/commands/common

Make ceph services wait for microcephd and force a config rewrite on startup. This should help avoid config inconsistencies and races.
Manual tests, standard CI testing

Sequence startup and rewrite config

---

docs/.sphinx/requirements.txt
docs/conf.py

We need a warning banner for when a user is not on the latest stable version of our documentation. `sphinx-version-warning` is a Sphinx extension that compares the current version to the latest one and then displays this banner at the top of the documentation page if it is an older version.

Add sphinx-version-warning extension

---

.github/workflows/tests.yml

The newly introduced `Test maintenance mode` job was failing due to using an outdated version of `actions/download-artifact`
This is a CI fix, it's tested by having this CI green

fix: Use download-artifact@v4

---

microceph/ceph/rgw.go
microceph/ceph/rgw_test.go

In #355 a regression was added where the `--port` rgw option is not respected.
This PR fixes this regression, updates the tests in order to ensure that it is respected in all contexts.
Fixes #483 
The unit tests were updated to reflect that change and confirm that the option is respected when it is passed.

fix: rgw --port is not respected

---

microceph/cmd/microcephd/main.go

They were turned on by default in f1e0421.
Fixes #491.
N/A

microceph/cmd/microcephd/main: turn --verbose and --debug logs off by default

---

microceph/ceph/osd.go

Follow-up of: 992abdf578de98443345559a7183d0b3e00e7b03
Having no redundancy of data is a warning and we shouldn't mute it out of the box since users must know those status. If they really want to mute the warning explicitly on purpose, they can do so on their own by issuing:
ceph health mute POOL_NO_REDUNDANCY
The automatic mute cause more issues than the benefit for example in the following cases.
Closes: #490
Related-Bug: [LP: #2104017](https://bugs.launchpad.net/snap-openstack/+bug/2104017)
Related-Bug: [LP: #2096921](https://bugs.launchpad.net/snap-openstack/+bug/2096921)
Please delete options that …

Don't mute any warning unless an user explicitly does it

---

.github/workflows/commits.yml

Pin ext. actions to SHA hash to prevent supply-chain attacks

Update CLA check and pin ext. actions

---

microceph/ceph/bootstrap.go
microceph/ceph/bootstrap_test.go

Wait for MON to become active before returning after bootstrapping
Fixes #473 
Updated unit tests

Fix: Wait for monitor responsiveness during bootstrap

---

snap/snapcraft.yaml

Pins Dqlite dependency to v1.18.0
If it fixes a reported issue, mention it here, i.e.:
Fixes #<issue-number>
- Bug fix (non-breaking change which fixes an issue)
Existing CI

chore: Pinned Dqlite dependency to 1.18.0

---

microceph/cmd/microceph/replication_status.go
tests/scripts/actionutils.sh

Fix incorrect status command keyword for RBD resources
Fixes #548 

Fixes RBD Replication status command

---

.github/workflows/tests.yml
microceph/ceph/replication_rbd.go
tests/scripts/actionutils.sh

This change adds a validation check to prevent users from enabling snapshot-based replication on RBD pools, which is currently unsupported. If a user attempts this, the system now returns a clear and descriptive error message.
This improves user experience by avoiding silent failures and preventing unexpected fallback to journal mode.
Fixes: #547
- ✅ Bug fix (non-breaking change which fixes an issue)
I tested this manually using my local build of MicroCeph (custom snap package) installed in `--devmode` in two clean Multipass VMs:
- **micro01** and **micro02** were set up as separate Ceph clusters using `microceph cluster bootstrap`.
- Fake disks were created using loopback devices on both VMs (`fallocate` + `losetup`) and added using `microceph disk add`.
- The two clusters were linked …

fix: prevent enabling snapshot replication on RBD pools

---

docs/.custom_wordlist.txt
docs/how-to/enable-service-instances.rst
docs/reference/commands/disable.rst
docs/reference/commands/enable.rst
microceph/cmd/microceph/disable_nfs.go
microceph/cmd/microceph/enable_nfs.go

Adds information about how to `enable nfs` in MicroCeph.
Depends-On: https://github.com/canonical/microceph/pull/574
- Documentation update (change to documentation only)
N/A

docs: Updates documentation to include information about enabling NFS

---

microceph/ceph/osd.go
microceph/ceph/osd_test.go

Necessary as plain dd did not reliably wipe the bdev
Fixes #617

fix: use ceph-bluestore-tool for wiping

---

snap/snapcraft.yaml
snapcraft/commands/ceph-authtool
snapcraft/commands/ceph-bluestore-tool

Expose the ceph-bluestore-tool for manipulating disk devices and the ceph-authtool for keyring files
- New feature (non-breaking change which adds functionality)
Manual testing, as we're only exposing existing upstream tools

feat: expose useful tools
